export const siteConfig = {
  name: "ClarkNet Telecom",
  slogan: "CONECTANDO VOCÊ AO MUNDO!",
  phone: "+55 67 99601-6225",
  whatsapp: "https://wa.me/5567996016225",
  instagram: "https://www.instagram.com/clarknet.telecom/",
  facebook: "#", // Configurable
  address: {
    street: "Avenida Genário da Costa Mattos",
    number: "955",
    city: "Deodápolis",
    state: "MS",
    zip: "79790-000",
  },
  officeHours: {
    weekdays: "Seg-Sex: 08h-11h | 13h-18h",
    saturday: "Sáb: 08h-12h",
    sunday: "Dom: Fechado",
  },
  cities: [
    "Deodápolis",
    "Lagoa Bonita",
    "Presidente Castelo",
    "Vila União",
    "Porto Vilma",
    "Ipezal",
  ],
  plans: [
    {
      id: "conecta",
      name: "Plano Conecta",
      speed: "500",
      speedUnit: "Mega",
      price: "109,90",
      benefits: [
        "Conexão estável",
        "Suporte 24h",
        "Instalação rápida",
      ],
      featured: false,
      whatsappMessage: "Olá, ClarkNet! Tenho interesse no Plano Conecta de 500 Mega por R$ 109,90/mês. Quero consultar disponibilidade.",
    },
    {
      id: "ultra",
      name: "Plano Ultra",
      speed: "800",
      speedUnit: "Mega",
      price: "179,90",
      benefits: [
        "Clark Play incluso",
        "Mais de 100 canais de TV e áudio",
        "Mais de 4 mil filmes e séries no streaming",
      ],
      featured: true,
      whatsappMessage: "Olá, ClarkNet! Tenho interesse no Plano Ultra de 800 Mega por R$ 179,90/mês. Quero consultar disponibilidade e condições para o meu endereço.",
    },
  ],
  ruralPlans: [
    {
      id: "rural-8mb",
      name: "Plano Rural",
      speed: "8",
      speedUnit: "MB",
      price: "103,00",
      benefits: [
        "Conexão via Rádio",
        "Rio Dourado e Porto Vilma",
        "Suporte Técnico Local",
      ],
      featured: false,
      whatsappMessage: "Olá, ClarkNet! Tenho interesse no Plano Rural de 8MB por R$ 103,00/mês. Quero consultar disponibilidade.",
    },
    {
      id: "rural-10mb",
      name: "Plano Rural",
      speed: "10",
      speedUnit: "MB",
      price: "123,00",
      benefits: [
        "Conexão via Rádio",
        "Rio Dourado e Porto Vilma",
        "Suporte Técnico Local",
      ],
      featured: true,
      whatsappMessage: "Olá, ClarkNet! Tenho interesse no Plano Rural de 10MB por R$ 123,00/mês. Quero consultar disponibilidade.",
    },
    {
      id: "rural-20mb",
      name: "Plano Rural",
      speed: "20",
      speedUnit: "MB",
      price: "153,00",
      benefits: [
        "Conexão via Rádio",
        "Rio Dourado e Porto Vilma",
        "Suporte Técnico Local",
      ],
      featured: false,
      whatsappMessage: "Olá, ClarkNet! Tenho interesse no Plano Rural de 20MB por R$ 153,00/mês. Quero consultar disponibilidade.",
    },
  ],
  links: [
    { name: "Início", href: "/" },
    { name: "Planos", href: "/planos" },
    { name: "Clark Play", href: "/clark-play" },
    { name: "Cobertura", href: "/cobertura" },
    { name: "Nossa História", href: "/sobre" },
    { name: "Atendimento", href: "/atendimento" },
  ],
};
